#!/usr/bin/env python3
"""Scaffold a new LLM Wiki directory structure."""

import argparse
import os
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description="Scaffold a new LLM Wiki directory structure.")
    parser.add_argument("path", help="Path where the wiki root directory will be created")
    parser.add_argument("--name", default="my-wiki", help="Wiki directory name (default: my-wiki)")
    args = parser.parse_args()

    wiki_root = Path(args.path).resolve()

    dirs = [
        wiki_root / "raw",
        wiki_root / "pages" / "entities",
        wiki_root / "pages" / "concepts",
        wiki_root / "pages" / "sources",
        wiki_root / "pages" / "synthesis",
    ]

    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
        # create .gitkeep so dirs are preserved in git
        (d / ".gitkeep").touch()

    # Schema file
    wiki_md = wiki_root / "WIKI.md"
    if not wiki_md.exists():
        wiki_md.write_text("""# Wiki Schema

This file defines the conventions for this LLM Wiki.

## Page Naming
- Use lowercase kebab-case: `machine-learning.md`, `attention-mechanism.md`
- Entity pages: `pages/entities/<name>.md`
- Concept pages: `pages/concepts/<name>.md`
- Source summaries: `pages/sources/<source-name>.md`
- Synthesis pages: `pages/synthesis/<topic>.md`

## Frontmatter
Every page should include YAML frontmatter:
```
---
title: <Page Title>
created: YYYY-MM-DD
tags: [tag1, tag2]
sources: [source1, source2]  # for pages derived from sources
---
```

## Page Format
- Start with frontmatter
- Use `## Overview` as first content heading
- Include cross-references using wiki-style links: `[[page-name]]` (Obsidian format)
- End with a `## See also` section linking related pages

## Ingest Workflow
1. Read the raw source
2. Write a source summary page in `pages/sources/`
3. Update entity/concept pages as needed
4. Update `index.md`
5. Append to `log.md`

## Lint Checks
- Orphan pages (no inbound links)
- Stale claims (superseded by newer sources)
- Missing cross-references
- Missing concept pages for mentioned topics
- Broken links

## Optional Tools
- qmd: local search engine with BM25/vector + LLM re-ranking
- Marp: markdown-based slide decks
- Dataview: Obsidian frontmatter queries
""")

    # Index
    index_md = wiki_root / "index.md"
    if not index_md.exists():
        index_md.write_text("""# Wiki Index

Content-oriented catalog of all wiki pages.

## Entities
<!-- pages/entities/*.md -->

## Concepts
<!-- pages/concepts/*.md -->

## Sources
<!-- pages/sources/*.md -->

## Synthesis
<!-- pages/synthesis/*.md -->

---
_Last updated by LLM during ingest_
""")

    # Log
    log_md = wiki_root / "log.md"
    if not log_md.exists():
        log_md.write_text("""# Wiki Log

Append-only chronological record. Prefix format: `## [YYYY-MM-DD] type | Title`

## Log Format
- `## [YYYY-MM-DD] init | Wiki initialized` — wiki creation
- `## [YYYY-MM-DD] ingest | Source Title` — source ingested
- `## [YYYY-MM-DD] query | Question summary` — query answered
- `## [YYYY-MM-DD] lint | Issues found: N` — lint pass
- `## [YYYY-MM-DD] update | Page name` — page updated

---
_Auto-generated by LLM_
""")

    print(f"Wiki scaffolded at: {wiki_root}")
    print("Next: Add sources to raw/ and run ingest workflow")


if __name__ == "__main__":
    main()